# basic options
title: Twenty-Two 
author: Mingya 
email: your-email@domain.com
description: A blog to caputre the jounery of my life after university 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: Sylhare/Type-on-Strap
