# basic options
title: New-awesome-blog
author: Smart Guy
email: your-email@domain.com
description: A wonderful site that captures the jounery of my life after university
twitter_username: potus
github_username:  evanwill

# Build settings
markdown: kramdown
theme: minima
