# basic options
title: 22
author: Mingya
email: your-email@domain.com
description: A wonderful site that captures the jounery of my life after university
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
