# basic options
title: Twenty-Two
author: Smart Guy
email: your-email@domain.com
description: A wonderful site that captures the jounery of my life after university
twitter_username: potus
github_username:  evanwill

# Build settings
markdown: kramdown
remote_theme: techieshark/strongly-typed-jekylled
