# basic options
title: Twenty-Two 
author: Mingya 
description: A blog to caputre the jounery of my life after university 
twitter_username: @Mingah_02
github_username:  zhongmingya

# Build settings
markdown: kramdown
remote_theme: iwiedenm/jekyll-theme-massively-src
